version: "3"
services:
  cracker-proxy:
    container_name: cracker-proxy-dev
    image: nginx:1.19-alpine
    volumes:
      - ./cracker-proxy/nginx:/etc/nginx/conf.d
    ports:
      - 5000:5000
    command: ["nginx", "-g", "daemon off;"]

  cracker-db:
    image: mongo:4.4.0
    container_name: cracker-db-dev
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  cracker-client:
    container_name: cracker-client-dev
    build:
      context: ./cracker-client
      dockerfile: Dockerfile.dev
    stdin_open: true # Without this React webserver exits immediately after setup
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Webpack uses Chokidar for watching changes - this forces the use of polling in a virtual machine
      - HTTPS=true
      - SSL_CRT_FILE=nginx/fullchain.pem
      - SSL_KEY_FILE=nginx/privkey.pem
    volumes: # For webpack dev server to use our local files
      - ./cracker-client:/usr/src/app
    ports:
      - 443:3000 # For docker to now where to redirect HMR queries

  cracker-server:
    container_name: cracker-server-dev
    build:
      context: ./cracker-server
      dockerfile: Dockerfile.dev
    environment:
      - MONGODB_ADDRESS=cracker-db:27017
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./cracker-server:/usr/src/api
    ports:
      - 4000:4000
    depends_on:
      - "cracker-db"

volumes:
  mongodb_data:
    driver: local
