version: "3"

services:
  cracker-db:
    image: mongo:4.2.6
    networks:
      - cracknet
    ports:
      - "27017:27017"

  cracker-client:
    image: mjgasior/cracker-client:latest
    networks:
      - cracknet
    ports:
      - "80:80"

  cracker-server:
    image: mjgasior/cracker-server:latest
    environment:
      - MONGODB_ADDRESS=cracker-db:27017
      - REACT_APP_AUTH0_ORIGIN=http://3.125.33.234
      - REACT_APP_API_URL=http://3.125.33.234/api
    networks:
      - cracknet

networks:
  cracknet:
    driver: bridge
