version: "3"

services:
  cracker-db:
    container_name: cracker-db
    image: mongo:4.2.6
    networks:
      - cracknet
    ports:
      - "27017:27017"

  cracker-client:
    container_name: cracker-client
    build:
      context: ./cracker-client
    networks:
      - cracknet
    ports:
      - "80:80"
      - "443:443"

  cracker-server:
    container_name: cracker-server
    build:
      context: ./cracker-server
    environment:
      - MONGODB_ADDRESS=cracker-db:27017
    networks:
      - cracknet

networks:
  cracknet:
    driver: bridge
