version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: "10.4"
    working_directory: ~/cracker-app
    steps:
      - checkout
      - run: pwd
      - run:
          name: Show files
          working_directory: ./cracker-client
          command: ls
      - node/with-cache:
          working_directory: ./cracker-client
          steps:
            - run:
                name: Install dependencies
                command: npm ci
      - run:
          name: Run tests
          working_directory: ./cracker-client
          command: npm run test
