query getMarkers($language: String) {
  getMarkers(language: $language) {
    _id
    imageFilename
    polish {
      name
      description
    }
    english {
      name
      description
    }
  }
}
