version: "3"

services:
  certbot:
    container_name: cracker-certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  cracker-db:
    container_name: cracker-db
    image: mongo:4.4.0
    networks:
      - cracknet
    ports:
      - "27017:27017"
    volumes:
      - ./../database:/data/db

  cracker-client:
    container_name: cracker-client
    image: mjgasior/cracker-client:0.0.3
    networks:
      - cracknet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  cracker-server:
    container_name: cracker-server
    image: mjgasior/cracker-server:0.0.1
    environment:
      - MONGODB_ADDRESS=cracker-db:27017
      - NODE_ENV=production
    networks:
      - cracknet
    volumes:
      - ./../images:/src/app/images

networks:
  cracknet:
    driver: bridge
