version: "3"

# this file is used to run the already built images
# it doesn't have the build phase at all
services:
  cracker-client:
    image: cracker-client:v4
    networks:
      - cracknet
    ports:
      - "80:80"

  crackback:
    image: cracker-server:v1
    networks:
      - cracknet

networks:
  cracknet:
    driver: bridge
